### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/postcss-ignore-plugin#1]
#TODO

## 1. comment to ignore the whole rules (done at #4 )

```css
/* postcss-ignore */
ul {
  color: red;
}
```

## 2. comment to ignore a specific plugin instead of all

This is just an IDEA 💡 , we need to refactor all cssnano plugins in order to support this.
MIght face some perf issues

```css
/* postcss-ignore-line :postcss-discard-unused: */
```

## 3. Tests

---

## 1. Tests for each package

- [X] `cssnano-ignore-remove` (Kickstarted at https://github.com/anikethsaha/cssnano-ignore-plugin/commit/eae32324f3e4a54a148a17b5ad7625ba551ac0d5)
- [X] `cssnano-ignore-add` (Kickstarted at https://github.com/anikethsaha/cssnano-ignore-plugin/commit/5861d17c85144621f93aa42eabbaf52e49158cf0)

## 2. Integration test

- [X] with cssnano (Kickstarted at https://github.com/anikethsaha/cssnano-ignore-plugin/commit/b2e55ce53ae4016a7d53e8412abb55be594448b0)
- [x] with some other plugins

## 4. comment to ignore the whole rules

```css
/* cssnano-ignore */
ul {
  color: red;
}
```

## 5. comment to ignore a specific plugin instead of all

This is just an IDEA 💡 , we need to refactor all cssnano plugins in order to support this.
MIght face some perf issues

```css
/* cssnano-ignore-line :postcss-discard-unused: */
```
